def get_table():
    table = {
        'j': [
            (11, 'ja'),
            (12, 'jac'),
            (13, 'jackson, j.'),
            (14, 'jackson, s.'),
            (15, 'jaco'),
            (16, 'jacobi'),
            (17, 'jacobs'),
            (18, 'jacop'),
            (19, 'jacq'),
            (21, 'jacqui'),
            (22, 'jae'),
            (23, 'jaf'),
            (24, 'jag'),
            (25, 'jah'),
            (26, 'jal'),
            (27, 'jam'),
            (28, 'james, m.'),
            (29, 'james, s.'),
            (31, 'jameso'),
            (32, 'jami'),
            (33, 'jan'),
            (34, 'jann'),
            (35, 'jans'),
            (36, 'jaq'),
            (37, 'jar'),
            (38, 'jarv'),
            (39, 'jas'),
            (41, 'jau'),
            (42, 'jay'),
            (43, 'je'),
            (44, 'jeb'),
            (45, 'jef'),
            (46, 'jeffre'),
            (47, 'jeffri'),
            (49, 'jem'),
            (51, 'jen'),
            (52, 'jenk'),
            (53, 'jenks'),
            (54, 'jenn'),
            (55, 'jer'),
            (56, 'jero'),
            (57, 'jerv'),
            (58, 'jes'),
            (59, 'jew'),
            (61, 'ji'),
            (62, 'jo'),
            (63, 'joc'),
            (64, 'joe'),
            (65, 'joh'),
            (66, 'johnso'),
            (67, 'johnson, g.'),
            (68, 'johnson, m.'),
            (69, 'johnson, s.'),
            (71, 'johnson, w.'),
            (72, 'johnst'),
            (73, 'johnston, m.'),
            (74, 'joi'),
            (75, 'jol'),
            (76, 'jon'),
            (77, 'jones, g.'),
            (78, 'jones, m.'),
            (79, 'jones, s.'),
            (81, 'jons'),
            (82, 'jor'),
            (83, 'jos'),
            (84, 'joss'),
            (85, 'jot'),
            (86, 'jou'),
            (87, 'jow'),
            (88, 'joy'),
            (89, 'joyc'),
            (91, 'ju'),
            (92, 'jud'),
            (93, 'juds'),
            (94, 'jul'),
            (95, 'jun'),
            (96, 'jus'),
            (97, 'juv'),
            (98, 'jux'),
            (99, 'jy')
        ]
    }
    return table
