def get_table():
    table = {
        'y': [
            (11, 'ya'),
            (12, 'yac'),
            (13, 'yah'),
            (14, 'yai'),
            (15, 'yak'),
            (16, 'yal'),
            (17, 'yale'),
            (18, 'yale, m.'),
            (19, 'yales'),
            (21, 'yan'),
            (22, 'yane'),
            (23, 'yani'),
            (24, 'yann'),
            (25, 'yao'),
            (26, 'yar'),
            (27, 'yard'),
            (28, 'yarf'),
            (29, 'yarr'),
            (31, 'yat'),
            (32, 'yates, g.'),
            (33, 'yates, m.'),
            (34, 'yates, s.'),
            (35, 'yatm'),
            (36, 'yb'),
            (37, 'ye'),
            (38, 'yeam'),
            (39, 'year'),
            (41, 'yeat'),
            (42, 'yeb'),
            (43, 'yef'),
            (44, 'yem'),
            (45, 'yen'),
            (46, 'yeo'),
            (47, 'yep'),
            (48, 'yet'),
            (49, 'yez'),
            (51, 'yh'),
            (52, 'yl'),
            (53, 'yn'),
            (54, 'yo'),
            (55, 'yon'),
            (56, 'yonge, g.'),
            (57, 'yonge, m.'),
            (58, 'yonge, s.'),
            (59, 'yonge, w.'),
            (61, 'yor'),
            (62, 'york, j.'),
            (63, 'york, p.'),
            (64, 'yorke'),
            (65, 'yorke, m.'),
            (66, 'yot'),
            (67, 'you'),
            (68, 'young'),
            (69, 'young, c.'),
            (71, 'young, e.'),
            (72, 'young, g.'),
            (73, 'young, j.'),
            (74, 'young, m.'),
            (75, 'young, p.'),
            (76, 'young, s.'),
            (77, 'young, t.'),
            (78, 'young, w.'),
            (79, 'youngm'),
            (81, 'youngs'),
            (82, 'yous'),
            (83, 'youss'),
            (84, 'yoz'),
            (85, 'yp'),
            (86, 'yps'),
            (87, 'yr'),
            (88, 'yri'),
            (89, 'yrie'),
            (91, 'ys'),
            (92, 'ysen'),
            (93, 'yss'),
            (94, 'yu'),
            (95, 'yule'),
            (96, 'yv'),
            (97, 'yve'),
            (98, 'yves'),
            (99, 'yvo')
        ]
    }
    return table
